import { defineCases } from "../case-types.js";

const accountSource = [
  {
    path: "packages/sdk/src/provable/account.ts",
    symbols: [
      "Account",
      "Timing",
      "Permission",
      "Permissions",
      "Zkapp",
      "packToFields",
    ],
  },
  {
    path: "packages/sdk/src/ledgers/staking-ledger/staking-ledger.ts",
    symbols: ["accountHashPrefix", "BaseStakingLedger.setLeaf"],
  },
] as const;

const merkleSource = [
  {
    path: "packages/sdk/src/provable/merkle-tree/prefixed-merkle-tree.ts",
    symbols: [
      "PrefixedMerkleTree",
      "BasePrefixedMerkleWitness",
      "PrefixedMerkleWitness36",
      "PrefixedMerkleWitness255",
      "conditionalSwap",
    ],
  },
] as const;

export const primitiveCases = defineCases([
  {
    id: "PRIM-ACCOUNT-001",
    family: "PRIM-ACCOUNT",
    title: "Canonical empty account packing and hash",
    component: "Account encoding",
    sources: accountSource,
    claims: ["ORACLE", "EXTERNAL_PARITY"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-account-empty-v1",
    proofOff: {
      outcome: "accept",
      note: "The empty fields, packed fields, and hash match the pinned vector.",
    },
    proofOn: {
      outcome: "accept",
      note: "The empty fields, packed fields, and hash match proof-off and the pinned vector.",
    },
  },
  {
    id: "PRIM-ACCOUNT-002",
    family: "PRIM-ACCOUNT",
    title: "Account field order and packing widths",
    component: "Account encoding",
    sources: accountSource,
    claims: ["ORACLE", "CONSTRAINT"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-account-packing-v1",
    proofOff: {
      outcome: "accept",
      note: "Independent packing preserves the canonical field order and widths.",
    },
    proofOn: {
      outcome: "accept",
      note: "Checked packing matches the proof-off packed fields.",
    },
  },
  {
    id: "PRIM-ACCOUNT-003",
    family: "PRIM-ACCOUNT",
    title: "Balance and nonce boundary packing",
    component: "Account encoding",
    sources: accountSource,
    claims: ["ORACLE", "CONSTRAINT"],
    priority: "P1",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-account-numeric-boundaries-v1",
    proofOff: {
      outcome: "accept",
      note: "Zero, one, and maximum UInt64 and UInt32 values pack without truncation.",
    },
    proofOn: {
      outcome: "accept",
      note: "Checked packing matches each numeric boundary result.",
    },
  },
  {
    id: "PRIM-ACCOUNT-004",
    family: "PRIM-ACCOUNT",
    title: "Default and custom token separation",
    component: "Account encoding",
    sources: accountSource,
    claims: ["ORACLE", "EXTERNAL_PARITY"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-account-token-ids-v1",
    proofOff: {
      outcome: "accept",
      note: "Default and custom token IDs produce their pinned account commitments.",
    },
    proofOn: {
      outcome: "accept",
      note: "Token commitments match proof-off and the pinned vectors.",
    },
  },
  {
    id: "PRIM-ACCOUNT-005",
    family: "PRIM-ACCOUNT",
    title: "Token symbol packing boundaries",
    component: "Account encoding",
    sources: accountSource,
    claims: ["ORACLE", "CONSTRAINT"],
    priority: "P1",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-account-token-symbol-v1",
    proofOff: {
      outcome: "accept",
      note: "Empty, one-byte, and maximum-width token symbols use the 48-bit partition.",
    },
    proofOn: {
      outcome: "accept",
      note: "Checked token-symbol packing matches proof-off.",
    },
  },
  {
    id: "PRIM-ACCOUNT-006",
    family: "PRIM-ACCOUNT",
    title: "Timed and untimed account packing",
    component: "Account timing",
    sources: accountSource,
    claims: ["ORACLE", "CONSTRAINT", "EXTERNAL_PARITY"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-account-timing-v1",
    proofOff: {
      outcome: "accept",
      note: "Untimed and timed field partitions match the independent model and vectors.",
    },
    proofOn: {
      outcome: "accept",
      note: "Checked timing packing matches proof-off and the vectors.",
    },
  },
  {
    id: "PRIM-ACCOUNT-007",
    family: "PRIM-ACCOUNT",
    title: "Permission variant encodings",
    component: "Account permissions",
    sources: accountSource,
    claims: ["ORACLE", "CONSTRAINT", "EXTERNAL_PARITY"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-account-permission-variants-v1",
    proofOff: {
      outcome: "accept",
      note: "Impossible, none, proof, signature, and either use distinct canonical bits.",
    },
    proofOn: {
      outcome: "accept",
      note: "Checked permission bits match proof-off and the pinned vectors.",
    },
  },
  {
    id: "PRIM-ACCOUNT-008",
    family: "PRIM-ACCOUNT",
    title: "Permission field order and verification-key version",
    component: "Account permissions",
    sources: accountSource,
    claims: ["ORACLE", "CONSTRAINT"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-account-permission-order-v1",
    proofOff: {
      outcome: "accept",
      note: "Every permission and the verification-key version occupies its canonical position.",
    },
    proofOn: {
      outcome: "accept",
      note: "Checked permission ordering matches the independent packing model.",
    },
  },
  {
    id: "PRIM-ACCOUNT-009",
    family: "PRIM-ACCOUNT",
    title: "Canonical empty zkApp account data",
    component: "Account zkApp encoding",
    sources: accountSource,
    claims: ["ORACLE", "EXTERNAL_PARITY"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-account-zkapp-empty-v1",
    proofOff: {
      outcome: "accept",
      note: "Empty app state, action state, key, URI, and hash match the pinned vector.",
    },
    proofOn: {
      outcome: "accept",
      note: "The empty zkApp commitment matches proof-off and the pinned vector.",
    },
  },
  {
    id: "PRIM-ACCOUNT-010",
    family: "PRIM-ACCOUNT",
    title: "Populated zkApp field order and hash prefix",
    component: "Account zkApp encoding",
    sources: accountSource,
    claims: ["ORACLE", "CONSTRAINT"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-account-zkapp-populated-v1",
    proofOff: {
      outcome: "accept",
      note: "Populated zkApp fields use the documented order and account-domain prefix.",
    },
    proofOn: {
      outcome: "accept",
      note: "Checked zkApp hashing matches proof-off.",
    },
  },
  {
    id: "PRIM-ACCOUNT-011",
    family: "PRIM-ACCOUNT",
    title: "Account JSON round trip and empty delegate",
    component: "Account serialization",
    sources: accountSource,
    claims: ["HOST"],
    priority: "P1",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "primitive-account-json-roundtrip-v1",
    proofOff: {
      outcome: "accept",
      note: "Canonical JSON round trips and preserves an empty delegate.",
    },
    proofOn: {
      outcome: "accept",
      note: "The host serialization result is independent of proof mode.",
    },
  },
  {
    id: "PRIM-ACCOUNT-012",
    family: "PRIM-ACCOUNT",
    title: "Malformed account JSON fallback",
    component: "Account serialization",
    sources: accountSource,
    claims: ["HOST", "CHARACTERIZATION"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "characterization",
    policyIds: ["POL-019"],
    fixture: "primitive-account-json-malformed-v1",
    proofOff: {
      outcome: "record",
      note: "Record each malformed input that becomes Account.empty instead of rejecting.",
    },
    proofOn: {
      outcome: "record",
      note: "Record the same host fallback without calling it circuit enforcement.",
    },
  },
  {
    id: "PRIM-ACCOUNT-013",
    family: "PRIM-ACCOUNT",
    title: "Account commitment field mutations",
    component: "Account hashing",
    sources: accountSource,
    claims: ["ORACLE", "CONSTRAINT"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-account-field-mutations-v1",
    proofOff: {
      outcome: "accept",
      note: "Each independent semantic field mutation changes the expected commitment.",
    },
    proofOn: {
      outcome: "accept",
      note: "Checked commitments preserve every enumerated field mutation.",
    },
  },
  {
    id: "PRIM-ACCOUNT-014",
    family: "PRIM-ACCOUNT",
    title: "Unknown permission text rejection",
    component: "Account permissions",
    sources: accountSource,
    claims: ["HOST"],
    priority: "P1",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "primitive-account-permission-invalid-v1",
    proofOff: {
      outcome: "reject",
      failureClass: "INPUT_VALIDATION",
      note: "Permission.fromString rejects an unknown permission name.",
    },
    proofOn: {
      outcome: "reject",
      failureClass: "INPUT_VALIDATION",
      note: "Host input validation remains unchanged in proof-on mode.",
    },
  },
  {
    id: "PRIM-MERKLE-001",
    family: "PRIM-MERKLE",
    title: "Height-36 leaf-index domain",
    component: "Prefixed Merkle tree",
    sources: merkleSource,
    claims: ["ORACLE", "HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "primitive-merkle-height-36-domain-v1",
    proofOff: {
      outcome: "accept",
      note: "Height 36 exposes exactly 2^35 leaves and indices 0 through 2^35-1.",
    },
    proofOn: {
      outcome: "accept",
      note: "The host leaf domain is independent of proof mode.",
    },
  },
  {
    id: "PRIM-MERKLE-002",
    family: "PRIM-MERKLE",
    title: "Empty prefixed-tree root vectors",
    component: "Prefixed Merkle tree",
    sources: merkleSource,
    claims: ["ORACLE", "EXTERNAL_PARITY"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-merkle-empty-roots-v1",
    proofOff: {
      outcome: "accept",
      note: "Each empty root matches its independently produced prefix vector.",
    },
    proofOn: {
      outcome: "accept",
      note: "Empty roots match proof-off and the pinned vectors.",
    },
  },
  {
    id: "PRIM-MERKLE-003",
    family: "PRIM-MERKLE",
    title: "Incremental leaf update root",
    component: "Prefixed Merkle tree",
    sources: merkleSource,
    claims: ["ORACLE", "HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "primitive-merkle-incremental-root-v1",
    proofOff: {
      outcome: "accept",
      note: "Each incremental update produces the independent prefixed root.",
    },
    proofOn: {
      outcome: "accept",
      note: "Incremental host roots match proof-off.",
    },
  },
  {
    id: "PRIM-MERKLE-004",
    family: "PRIM-MERKLE",
    title: "Bulk fill and incremental update equivalence",
    component: "Prefixed Merkle tree",
    sources: merkleSource,
    claims: ["ORACLE", "HOST"],
    priority: "P1",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "primitive-merkle-fill-equivalence-v1",
    proofOff: {
      outcome: "accept",
      note: "Bulk fill and ordered leaf updates produce the same root.",
    },
    proofOn: {
      outcome: "accept",
      note: "The equivalent host roots match proof-off.",
    },
  },
  {
    id: "PRIM-MERKLE-005",
    family: "PRIM-MERKLE",
    title: "Partial fill uses the canonical empty suffix",
    component: "Prefixed Merkle tree",
    sources: merkleSource,
    claims: ["ORACLE", "HOST"],
    priority: "P1",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "primitive-merkle-partial-fill-v1",
    proofOff: {
      outcome: "accept",
      note: "A partial fill hashes populated leaves with the canonical empty suffix.",
    },
    proofOn: {
      outcome: "accept",
      note: "The partial-fill root matches proof-off.",
    },
  },
  {
    id: "PRIM-MERKLE-006",
    family: "PRIM-MERKLE",
    title: "Hash-prefix and level domain separation",
    component: "Prefixed Merkle tree",
    sources: merkleSource,
    claims: ["ORACLE", "CONSTRAINT"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-merkle-prefix-separation-v1",
    proofOff: {
      outcome: "accept",
      note: "Changing a prefix or its level changes the independent root.",
    },
    proofOn: {
      outcome: "accept",
      note: "Checked prefix separation matches proof-off.",
    },
  },
  {
    id: "PRIM-MERKLE-007",
    family: "PRIM-MERKLE",
    title: "Left and right child order commitment",
    component: "Prefixed Merkle tree",
    sources: merkleSource,
    claims: ["ORACLE", "CONSTRAINT"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-merkle-child-order-v1",
    proofOff: {
      outcome: "accept",
      note: "Swapping unequal children changes the root at the affected level.",
    },
    proofOn: {
      outcome: "accept",
      note: "Checked child ordering matches proof-off.",
    },
  },
  {
    id: "PRIM-MERKLE-008",
    family: "PRIM-MERKLE",
    title: "Witness root reconstruction",
    component: "Prefixed Merkle witness",
    sources: merkleSource,
    claims: ["ORACLE", "CONSTRAINT"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-merkle-witness-root-v1",
    proofOff: {
      outcome: "accept",
      note: "Witnesses reconstruct the committed root for boundary and interior leaves.",
    },
    proofOn: {
      outcome: "accept",
      note: "Checked witness roots match proof-off.",
    },
  },
  {
    id: "PRIM-MERKLE-009",
    family: "PRIM-MERKLE",
    title: "Witness index reconstruction",
    component: "Prefixed Merkle witness",
    sources: merkleSource,
    claims: ["ORACLE", "CONSTRAINT"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-merkle-witness-index-v1",
    proofOff: {
      outcome: "accept",
      note: "Witness direction bits reconstruct zero, interior, and maximum indices.",
    },
    proofOn: {
      outcome: "accept",
      note: "Checked witness indices match proof-off.",
    },
  },
  {
    id: "PRIM-MERKLE-010",
    family: "PRIM-MERKLE",
    title: "Witness leaf, sibling, and direction mutations",
    component: "Prefixed Merkle witness",
    sources: merkleSource,
    claims: ["ORACLE", "CONSTRAINT"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-merkle-witness-mutations-v1",
    proofOff: {
      outcome: "accept",
      note: "Each witness mutation fails to reconstruct the committed root or index.",
    },
    proofOn: {
      outcome: "accept",
      note: "Checked mutation results match proof-off.",
    },
  },
  {
    id: "PRIM-MERKLE-011",
    family: "PRIM-MERKLE",
    title: "Witness length rejection",
    component: "Prefixed Merkle witness",
    sources: merkleSource,
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "primitive-merkle-witness-length-v1",
    proofOff: {
      outcome: "reject",
      failureClass: "INPUT_VALIDATION",
      note: "A witness shorter or longer than height minus one rejects.",
    },
    proofOn: {
      outcome: "reject",
      failureClass: "INPUT_VALIDATION",
      note: "Witness length validation is independent of proof mode.",
    },
  },
  {
    id: "PRIM-MERKLE-012",
    family: "PRIM-MERKLE",
    title: "Maximum valid leaf index",
    component: "Prefixed Merkle tree",
    sources: merkleSource,
    claims: ["HOST", "CONSTRAINT"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-merkle-maximum-index-v1",
    proofOff: {
      outcome: "accept",
      note: "The maximum height-36 leaf index supports update and witness reconstruction.",
    },
    proofOn: {
      outcome: "accept",
      note: "Checked maximum-index reconstruction matches proof-off.",
    },
  },
  {
    id: "PRIM-MERKLE-013",
    family: "PRIM-MERKLE",
    title: "Upper-bound leaf index rejection",
    component: "Prefixed Merkle tree",
    sources: merkleSource,
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "primitive-merkle-upper-bound-v1",
    proofOff: {
      outcome: "reject",
      failureClass: "INPUT_VALIDATION",
      note: "setLeaf and getWitness reject index 2^35 for height 36.",
    },
    proofOn: {
      outcome: "reject",
      failureClass: "INPUT_VALIDATION",
      note: "The upper-bound rejection is independent of proof mode.",
    },
  },
  {
    id: "PRIM-MERKLE-014",
    family: "PRIM-MERKLE",
    title: "Negative leaf index rejection",
    component: "Prefixed Merkle tree",
    sources: merkleSource,
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "primitive-merkle-negative-index-v1",
    proofOff: {
      outcome: "reject",
      failureClass: "INPUT_VALIDATION",
      note: "setLeaf and getWitness must reject an index below zero.",
    },
    proofOn: {
      outcome: "reject",
      failureClass: "INPUT_VALIDATION",
      note: "The lower-bound rejection is independent of proof mode.",
    },
  },
  {
    id: "PRIM-MERKLE-015",
    family: "PRIM-MERKLE",
    title: "Bulk fill capacity rejection",
    component: "Prefixed Merkle tree",
    sources: merkleSource,
    claims: ["HOST"],
    priority: "P1",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "primitive-merkle-fill-capacity-v1",
    proofOff: {
      outcome: "reject",
      failureClass: "INPUT_VALIDATION",
      note: "fill rejects one leaf more than the tree capacity.",
    },
    proofOn: {
      outcome: "reject",
      failureClass: "INPUT_VALIDATION",
      note: "The fill-capacity rejection is independent of proof mode.",
    },
  },
  {
    id: "PRIM-MERKLE-016",
    family: "PRIM-MERKLE",
    title: "Height-255 symbolic index and witness boundaries",
    component: "Prefixed Merkle witness",
    sources: merkleSource,
    claims: ["ORACLE", "CONSTRAINT"],
    priority: "P1",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-merkle-height-255-symbolic-v1",
    proofOff: {
      outcome: "accept",
      note: "A symbolic fixture covers height-255 boundaries without allocating a complete tree.",
    },
    proofOn: {
      outcome: "accept",
      note: "Checked symbolic roots and indices match proof-off.",
    },
  },
  {
    id: "PRIM-MERKLE-017",
    family: "PRIM-MERKLE",
    title: "Staking, voting, and nullifier root vectors",
    component: "Ledger Merkle commitments",
    sources: [
      ...merkleSource,
      {
        path: "packages/sdk/src/ledgers/staking-ledger/staking-ledger.ts",
        symbols: ["accountLedgerHashPrefixes", "accountHashPrefix"],
      },
      {
        path: "packages/sdk/src/ledgers/voting-ledger/voting-ledger.ts",
        symbols: ["votingAccountLedgerHashPrefixes", "votingAccountHashPrefix"],
      },
      {
        path: "packages/sdk/src/ledgers/nullifier-ledger/nullifier-ledger.ts",
        symbols: ["nullifierLedgerHashPrefixes", "nullifierHashPrefix"],
      },
    ],
    claims: ["ORACLE", "EXTERNAL_PARITY"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "primitive-merkle-ledger-root-vectors-v1",
    proofOff: {
      outcome: "accept",
      note: "Ledger roots match independent vectors for every committed prefix family.",
    },
    proofOn: {
      outcome: "accept",
      note: "Ledger roots match proof-off and the pinned vectors.",
    },
  },
]);
