import { defineCases } from "../case-types.js";

const accept = (note: string) => ({ outcome: "accept" as const, note });
const record = (note: string) => ({ outcome: "record" as const, note });
const notApplicable = (note: string) => ({
  outcome: "not-applicable" as const,
  note,
});
const reject = <
  const T extends
    | "INPUT_VALIDATION"
    | "HOST_PREFLIGHT"
    | "CONSTRAINT_UNSATISFIED"
    | "PROOF_VERIFICATION"
    | "TRANSACTION_PRECONDITION"
    | "STORAGE_FAILURE"
    | "DEPENDENCY_FAILURE"
    | "TIMEOUT",
>(
  failureClass: T,
  note: string,
) => ({
  outcome: "reject" as const,
  failureClass,
  note,
});

const mergeSources = [
  {
    path: "packages/sdk/src/proving/prover/merge-proof-orchestrator.ts",
    symbols: ["MergeProofOrchestrator.merge", "MergeProofOrchestrator.persist"],
  },
] as const;

const stakingProofStorageSources = [
  {
    path: "packages/sdk/src/storage/keyv/keyv-staking-ledger-to-voting-ledger-proof-storage.ts",
    symbols: [
      "KeyvStakingLedgerToVotingLedgerProofStorage.getProof",
      "KeyvStakingLedgerToVotingLedgerProofStorage.setProof",
      "KeyvStakingLedgerToVotingLedgerProofStorage.getMergeProof",
      "KeyvStakingLedgerToVotingLedgerProofStorage.setMergeProof",
    ],
  },
] as const;

const voteProofStorageSources = [
  {
    path: "packages/sdk/src/storage/keyv/keyv-vote-reducer-proof-storage.ts",
    symbols: [
      "KeyvVoteReducerProofStorage.getProof",
      "KeyvVoteReducerProofStorage.setProof",
      "KeyvVoteReducerProofStorage.getMergeProof",
      "KeyvVoteReducerProofStorage.setMergeProof",
    ],
  },
] as const;

const queueSources = [
  {
    path: "packages/sdk/src/proving/task-queue.ts",
    symbols: [
      "TaskQueue.addTask",
      "TaskQueue.onTaskComplete",
      "TaskQueue.waitUntilEmpty",
      "TaskQueue.obliterate",
      "TaskQueue.close",
    ],
  },
] as const;

const workerSources = [
  {
    path: "packages/sdk/src/proving/worker.ts",
    symbols: [
      "Worker.createWorker",
      "Worker.workJob",
      "Worker.runSubprocessJobWithTimeout",
      "Worker.terminateSubprocess",
      "Worker.close",
    ],
  },
] as const;

const stakingServiceSources = [
  {
    path: "packages/sdk/src/services/sqlite/sqlite-staking-ledger-to-voting-ledger-service.ts",
    symbols: [
      "SqliteStakingLedgerToVotingLedgerService.start",
      "SqliteStakingLedgerToVotingLedgerService.traceDigest",
      "SqliteStakingLedgerToVotingLedgerService.proveDigest",
      "SqliteStakingLedgerToVotingLedgerService.proveMerge",
      "SqliteStakingLedgerToVotingLedgerService.proveExhaust",
      "SqliteStakingLedgerToVotingLedgerService.checkpointWal",
      "SqliteStakingLedgerToVotingLedgerService.writeCheckpointLedgerHash",
      "SqliteStakingLedgerToVotingLedgerService.readCheckpointLedgerHash",
      "SqliteStakingLedgerToVotingLedgerService.close",
    ],
  },
] as const;

const checkpointSources = [
  {
    path: "apps/cli/src/commands/staking-ledger-to-voting-ledger.ts",
    symbols: [
      "traceDigest",
      "checkpointRestore",
      "checkpointClean",
      "proveDigest",
      "proveMerge",
      "proveExhaust",
    ],
  },
  {
    path: "apps/cli/src/lib/s3-checkpoint.ts",
    symbols: ["pullCheckpoint", "pushCheckpoint", "cleanCheckpoint"],
  },
] as const;

const webProverSources = [
  {
    path: "apps/web/features/proposals/workers/treasury-proposal.worker.ts",
    symbols: ["adoptRuntimeConfig", "ensureCompiled"],
  },
  {
    path: "apps/web/features/proposals/lib/proposal-prover-runtime.ts",
    symbols: [
      "compileProposalContractsInCurrentThread",
      "applySerializedProposalCompileArtifactsInCurrentThread",
      "buildAndProveCreateProposalTransactionInCurrentThread",
      "buildAndProveVoteProposalTransactionInCurrentThread",
      "buildAndProveExecuteProposalTransactionInCurrentThread",
      "assertProofsPresent",
    ],
  },
] as const;

const projectionSources = [
  {
    path: "packages/indexer/src/events-indexer.ts",
    symbols: [
      "EventsIndexer.syncPendingOnce",
      "EventsIndexer.syncCanonicalOnce",
      "EventsIndexer.sweepOrphanedPendingEvents",
    ],
  },
  {
    path: "packages/indexer/src/events-repository.ts",
    symbols: [
      "EventsRepository.ingestRawEventsAndAdvanceCursor",
      "EventsRepository.markPendingAsOrphaned",
      "EventsRepository.immutableEventMatches",
    ],
  },
  {
    path: "packages/processor/src/events-processor.ts",
    symbols: [
      "EventsProcessor.processOnce",
      "EventsProcessor.retryBlockedEvent",
      "EventsProcessor.trySupersedeBlockedFailure",
    ],
  },
  {
    path: "apps/api/src/processors/proposals/proposal-projection-reconciler.ts",
    symbols: [
      "ProposalProjectionReconciler.recordAndReconcile",
      "ProposalProjectionReconciler.reconcileProposal",
      "ProposalProjectionReconciler.reconcileVotesAndTallies",
      "ProposalProjectionReconciler.reconcileExecutions",
    ],
  },
] as const;

const localBlockchainSources = [
  {
    path: "packages/local-blockchain/src/runtime/local-blockchain-runtime.ts",
    symbols: [
      "LocalBlockchainRuntime.submitTransaction",
      "LocalBlockchainRuntime.captureArchiveEvents",
      "LocalBlockchainRuntime.getAccount",
      "LocalBlockchainRuntime.fetchArchiveEvents",
      "LocalBlockchainRuntime.fetchArchiveActions",
    ],
  },
  {
    path: "packages/local-blockchain/test/fixtures/submit-full-treasury-flow-from-separate-process.ts",
    symbols: ["main"],
  },
] as const;

export const systemCases = defineCases([
  {
    id: "ART-PROOF-001",
    family: "ART-PROOF",
    title: "Serialized proof payload round trip",
    component: "proof artifact transport",
    sources: stakingProofStorageSources,
    claims: ["PROOF_AUTHENTICITY"],
    priority: "P0",
    phasePolicy: "proof-authenticity",
    policyStatus: "conformance",
    fixture: "artifact-proof-roundtrip-seed-001",
    proofOff: record("The proof-off payload records the capability boundary."),
    proofOn: accept(
      "The decoded proof verifies with its expected program and key.",
    ),
  },
  {
    id: "ART-PROOF-002",
    family: "ART-PROOF",
    title: "Truncated proof JSON rejection",
    component: "proof artifact transport",
    sources: stakingProofStorageSources,
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "transport-only",
    policyStatus: "conformance",
    fixture: "artifact-json-truncation-partitions-seed-002",
    proofOff: reject(
      "INPUT_VALIDATION",
      "Each truncation partition fails decoding.",
    ),
    proofOn: reject(
      "INPUT_VALIDATION",
      "Each truncation partition fails before verification.",
    ),
  },
  {
    id: "ART-PROOF-003",
    family: "ART-PROOF",
    title: "Missing required proof fields rejection",
    component: "proof artifact transport",
    sources: voteProofStorageSources,
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "transport-only",
    policyStatus: "conformance",
    fixture: "artifact-required-field-omissions-seed-003",
    proofOff: reject(
      "INPUT_VALIDATION",
      "Every required-field omission fails decoding.",
    ),
    proofOn: reject(
      "INPUT_VALIDATION",
      "Every required-field omission fails before verification.",
    ),
  },
  {
    id: "ART-PROOF-004",
    family: "ART-PROOF",
    title: "Unknown proof JSON field policy",
    component: "proof artifact transport",
    sources: [...stakingProofStorageSources, ...voteProofStorageSources],
    claims: ["UNRESOLVED"],
    priority: "P1",
    phasePolicy: "transport-only",
    policyStatus: "unresolved",
    policyIds: ["POL-019"],
    fixture: "artifact-unknown-field-depths-seed-004",
    proofOff: record(
      "Record whether each decoder accepts or rejects unknown fields.",
    ),
    proofOn: record(
      "Record the same decoder behavior before proof verification.",
    ),
  },
  {
    id: "ART-PROOF-005",
    family: "ART-PROOF",
    title: "Duplicate replay operation rejection",
    component: "proof replay",
    sources: stakingProofStorageSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "artifact-replay-duplicate-seed-005",
    proofOff: reject(
      "INPUT_VALIDATION",
      "A duplicated replay operation does not change durable state.",
    ),
    proofOn: reject(
      "INPUT_VALIDATION",
      "The same duplicate fails without proof-authenticity credit.",
    ),
  },
  {
    id: "ART-PROOF-006",
    family: "ART-PROOF",
    title: "Reordered replay operation rejection",
    component: "proof replay",
    sources: voteProofStorageSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "artifact-replay-permutations-seed-006",
    proofOff: reject(
      "INPUT_VALIDATION",
      "A reordered replay sequence does not change durable state.",
    ),
    proofOn: reject(
      "INPUT_VALIDATION",
      "The same reordering fails without proof-authenticity credit.",
    ),
  },
  {
    id: "ART-PROOF-007",
    family: "ART-PROOF",
    title: "Public input mutation rejection",
    component: "proof verifier context",
    sources: stakingProofStorageSources,
    claims: ["PROOF_AUTHENTICITY"],
    priority: "P0",
    phasePolicy: "proof-authenticity",
    policyStatus: "conformance",
    fixture: "artifact-public-input-mutations-seed-007",
    proofOff: record(
      "The negative control shows that proof-off cannot authenticate the input.",
    ),
    proofOn: reject(
      "PROOF_VERIFICATION",
      "Verification rejects each changed public input.",
    ),
  },
  {
    id: "ART-PROOF-008",
    family: "ART-PROOF",
    title: "Public output mutation rejection",
    component: "proof verifier context",
    sources: voteProofStorageSources,
    claims: ["PROOF_AUTHENTICITY"],
    priority: "P0",
    phasePolicy: "proof-authenticity",
    policyStatus: "conformance",
    fixture: "artifact-public-output-mutations-seed-008",
    proofOff: record(
      "The negative control shows that proof-off cannot authenticate the output.",
    ),
    proofOn: reject(
      "PROOF_VERIFICATION",
      "Verification rejects each changed public output.",
    ),
  },
  {
    id: "ART-PROOF-009",
    family: "ART-PROOF",
    title: "Verification key substitution rejection",
    component: "proof verifier context",
    sources: [...stakingProofStorageSources, ...voteProofStorageSources],
    claims: ["PROOF_AUTHENTICITY"],
    priority: "P0",
    phasePolicy: "proof-authenticity",
    policyStatus: "conformance",
    fixture: "artifact-cross-program-vk-seed-009",
    proofOff: record(
      "The negative control shows that proof-off cannot authenticate the key.",
    ),
    proofOn: reject(
      "PROOF_VERIFICATION",
      "Verification rejects a valid proof under each wrong key.",
    ),
  },
  {
    id: "ART-PROOF-010",
    family: "ART-PROOF",
    title: "Circuit and o1js revision mismatch rejection",
    component: "proof verifier context",
    sources: mergeSources,
    claims: ["PROOF_AUTHENTICITY"],
    priority: "P0",
    phasePolicy: "proof-authenticity",
    policyStatus: "conformance",
    fixture: "artifact-revision-mismatch-seed-010",
    proofOff: record(
      "The controller records the revision mismatch capability boundary.",
    ),
    proofOn: reject(
      "HOST_PREFLIGHT",
      "The controller rejects a circuit or o1js revision mismatch before reuse.",
    ),
  },
  {
    id: "ART-PROOF-011",
    family: "ART-PROOF",
    title: "Trace content change under stable storage ID",
    component: "proof artifact identity",
    sources: stakingProofStorageSources,
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "unresolved",
    policyIds: ["POL-022"],
    fixture: "artifact-stable-id-trace-change-seed-011",
    proofOff: record(
      "Expose whether storage identity binds the changed trace digest.",
    ),
    proofOn: record(
      "Expose the same binding gap; process mode does not authenticate storage identity.",
    ),
  },
  {
    id: "ART-PROOF-012",
    family: "ART-PROOF",
    title: "Proof content change under stable merge ID",
    component: "merge proof cache identity",
    sources: mergeSources,
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "proof-authenticity",
    policyStatus: "unresolved",
    policyIds: ["POL-022", "POL-032"],
    fixture: "artifact-stable-merge-id-proof-change-seed-012",
    proofOff: record(
      "Expose whether child content participates in the merge cache key.",
    ),
    proofOn: reject(
      "PROOF_VERIFICATION",
      "A changed cached proof must fail verification before return.",
    ),
  },
  {
    id: "ART-PROOF-013",
    family: "ART-PROOF",
    title: "Proof-off cache reuse in proof-on rejection",
    component: "compile and proof cache isolation",
    sources: mergeSources,
    claims: ["PROOF_AUTHENTICITY"],
    priority: "P0",
    phasePolicy: "proof-authenticity",
    policyStatus: "conformance",
    fixture: "artifact-cross-mode-cache-seed-013",
    proofOff: accept("Create only a mode-keyed proof-off cache entry."),
    proofOn: reject(
      "HOST_PREFLIGHT",
      "Reject the proof-off cache namespace before proof-on work.",
    ),
  },
  {
    id: "ART-PROOF-014",
    family: "ART-PROOF",
    title: "Cross-lifecycle or cross-build proof reuse",
    component: "proof artifact identity",
    sources: [...stakingProofStorageSources, ...voteProofStorageSources],
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "unresolved",
    policyIds: ["POL-006", "POL-022"],
    fixture: "artifact-lifecycle-build-cross-product-seed-014",
    proofOff: record(
      "Expose whether lifecycle and build values bind proof storage identity.",
    ),
    proofOn: record(
      "Expose the same operational binding separately from proof validity.",
    ),
  },
  {
    id: "ART-PROOF-015",
    family: "ART-PROOF",
    title: "Provenance applicability and missing binding inventory",
    component: "proof artifact provenance",
    sources: [...stakingProofStorageSources, ...voteProofStorageSources],
    claims: ["UNRESOLVED"],
    priority: "P1",
    phasePolicy: "transport-only",
    policyStatus: "unresolved",
    policyIds: ["POL-022", "POL-023"],
    fixture: "artifact-provenance-field-applicability-seed-015",
    proofOff: record(
      "Record every required, present, missing, and not-applicable provenance field.",
    ),
    proofOn: record(
      "Record the same inventory and do not call metadata a circuit binding.",
    ),
  },
  {
    id: "ART-PROOF-016",
    family: "ART-PROOF",
    title: "Replaced base proof under stable storage ID",
    component: "base proof cache identity",
    sources: [...stakingProofStorageSources, ...mergeSources],
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "proof-authenticity",
    policyStatus: "unresolved",
    policyIds: ["POL-022", "POL-032"],
    fixture: "artifact-base-proof-replacement-seed-016",
    proofOff: record(
      "Expose whether replacement invalidates the dependent merge cache.",
    ),
    proofOn: reject(
      "PROOF_VERIFICATION",
      "Reject the replacement before storage or cache publication.",
    ),
  },
  {
    id: "ART-PROOF-017",
    family: "ART-PROOF",
    title: "Corrupt cached root proof rejection",
    component: "root proof cache",
    sources: mergeSources,
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "proof-authenticity",
    policyStatus: "unresolved",
    policyIds: ["POL-032"],
    fixture: "artifact-corrupt-root-proof-seed-017",
    proofOff: record(
      "The negative control records that cache presence is not authenticity.",
    ),
    proofOn: reject(
      "PROOF_VERIFICATION",
      "Verify and reject the corrupt root before return.",
    ),
  },
  {
    id: "ART-PROOF-018",
    family: "ART-PROOF",
    title: "Later compatible merge pair selection",
    component: "merge proof candidate search",
    sources: [
      ...mergeSources,
      {
        path: "packages/sdk/src/proving/prover/vote-reducer-prover.ts",
        symbols: ["VoteReducerProver.findMergeableProofs"],
      },
    ],
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "artifact-multiple-merge-candidates-seed-018",
    proofOff: accept(
      "Skip the incompatible first pair and return the later valid pair.",
    ),
    proofOn: accept(
      "Return the same pair without assigning proof-authenticity credit.",
    ),
  },
  {
    id: "ART-PROOF-019",
    family: "ART-PROOF",
    title: "Committed proof artifact provenance inventory",
    component: "repository proof fixtures",
    sources: [
      {
        path: "apps/cli/test/fixtures/proposal-tally-votes-state.json",
        symbols: ["committed proposal tally fixture"],
      },
      {
        path: "apps/cli/artifacts/exhausted-proof.json",
        symbols: ["serialized exhausted proof payload"],
      },
      {
        path: "apps/cli/artifacts/merged-proof.json",
        symbols: ["serialized merged proof payload"],
      },
    ],
    claims: ["STATIC_ONLY"],
    priority: "P1",
    phasePolicy: "transport-only",
    policyStatus: "conformance",
    fixture: "artifact-repository-inventory-seed-019",
    proofOff: record(
      "Inventory reproducible source, key, program, lifecycle, ledger, build, and chain data.",
    ),
    proofOn: record("Use the same immutable inventory in the proof-on report."),
  },

  {
    id: "OPS-QUEUE-001",
    family: "OPS-QUEUE",
    title: "Queue completion before listener setup",
    component: "task queue completion",
    sources: queueSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "queue-immediate-completion-seed-101",
    proofOff: accept(
      "An immediate completion resolves the matching task exactly once.",
    ),
    proofOn: accept(
      "The same completion race resolves without authenticity credit.",
    ),
  },
  {
    id: "OPS-QUEUE-002",
    family: "OPS-QUEUE",
    title: "Duplicate completion event handling",
    component: "task queue completion",
    sources: queueSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "queue-duplicate-completion-seed-102",
    proofOff: accept(
      "Duplicate completion events cause one resolution and one cleanup.",
    ),
    proofOn: accept(
      "The same idempotent result occurs in the proof-on process.",
    ),
  },
  {
    id: "OPS-QUEUE-003",
    family: "OPS-QUEUE",
    title: "Delayed unrelated job isolation",
    component: "task queue listeners",
    sources: queueSources,
    claims: ["RESILIENCE"],
    priority: "P1",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "queue-delayed-interleaving-seed-103",
    proofOff: accept("Only the matching job completes the waiting caller."),
    proofOn: accept("The matching rule is unchanged in the proof-on process."),
  },
  {
    id: "OPS-QUEUE-004",
    family: "OPS-QUEUE",
    title: "Completion and failure listener cleanup",
    component: "task queue listeners",
    sources: queueSources,
    claims: ["HOST"],
    priority: "P1",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "queue-listener-cleanup-seed-104",
    proofOff: accept(
      "Success, failure, and decode error remove both job listeners.",
    ),
    proofOn: accept("The proof-on process leaves the same listener count."),
  },
  {
    id: "OPS-QUEUE-005",
    family: "OPS-QUEUE",
    title: "Retry exhaustion and retained failure",
    component: "task queue retry",
    sources: queueSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "queue-retry-exhaustion-seed-105",
    proofOff: reject(
      "DEPENDENCY_FAILURE",
      "Bounded retries end in a visible retained failure.",
    ),
    proofOn: reject(
      "DEPENDENCY_FAILURE",
      "Bounded retries have the same final failure class.",
    ),
  },
  {
    id: "OPS-QUEUE-006",
    family: "OPS-QUEUE",
    title: "Permanently failing oldest lifecycle does not hide later work",
    component: "proof scheduler liveness",
    sources: queueSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "queue-blocked-oldest-lifecycle-seed-106",
    proofOff: accept(
      "Later independent work reaches a bounded terminal result.",
    ),
    proofOn: accept("Later independent work has the same liveness result."),
  },
  {
    id: "OPS-QUEUE-007",
    family: "OPS-QUEUE",
    title: "Queue ownership and obliteration isolation",
    component: "proof scheduler ownership",
    sources: [...queueSources, ...mergeSources],
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "unresolved",
    policyIds: ["POL-021"],
    fixture: "queue-two-owner-lifecycle-seed-107",
    proofOff: record(
      "Expose whether one scheduler can obliterate another scheduler's work.",
    ),
    proofOn: record(
      "Expose the same ownership behavior in the proof-on process.",
    ),
  },
  {
    id: "OPS-QUEUE-008",
    family: "OPS-QUEUE",
    title: "Proof job and retry identity isolation",
    component: "proof job identity",
    sources: [...queueSources, ...workerSources],
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "unresolved",
    policyIds: ["POL-022"],
    fixture: "queue-run-lifecycle-key-cross-product-seed-108",
    proofOff: record(
      "Expose every job and retry identity field that can cross a run.",
    ),
    proofOn: record(
      "Expose the same identity boundaries without authenticity credit.",
    ),
  },
  {
    id: "OPS-QUEUE-009",
    family: "OPS-QUEUE",
    title: "Worker timeout terminates and restarts its subprocess",
    component: "proof worker process",
    sources: workerSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "worker-timeout-restart-seed-109",
    proofOff: reject(
      "TIMEOUT",
      "The timed-out task fails and the next task uses a fresh subprocess.",
    ),
    proofOn: reject(
      "TIMEOUT",
      "The proof-on worker has the same bounded timeout behavior.",
    ),
  },
  {
    id: "OPS-QUEUE-010",
    family: "OPS-QUEUE",
    title: "Process Redis versus memory Redis evidence boundary",
    component: "Redis test infrastructure",
    sources: [
      {
        path: "packages/sdk/test/proving/task-queue.test.ts",
        symbols: ["RedisMemoryServer", "TaskQueue test suite"],
      },
      ...queueSources,
    ],
    claims: ["CHARACTERIZATION"],
    priority: "P2",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "queue-redis-evidence-boundary-seed-110",
    proofOff: record(
      "Label process-memory Redis evidence separately from deployed Redis evidence.",
    ),
    proofOn: record("Keep the same evidence label in the proof-on report."),
  },

  {
    id: "OPS-RESTART-001",
    family: "OPS-RESTART",
    title: "Stop before trace batch commit",
    component: "staking trace transaction",
    sources: stakingServiceSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "restart-before-trace-commit-seed-201",
    proofOff: accept(
      "A test adapter preserves the exact pre-state and no mixed write.",
    ),
    proofOn: accept(
      "The same storage invariant holds in the proof-on process.",
    ),
  },
  {
    id: "OPS-RESTART-002",
    family: "OPS-RESTART",
    title: "Stop between account and Merkle leaf writes",
    component: "staking trace atomicity",
    sources: stakingServiceSources,
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "unresolved",
    policyIds: ["POL-020"],
    fixture: "restart-account-leaf-split-seed-202",
    proofOff: record("Expose the account-written and leaf-failed host state."),
    proofOn: record(
      "Expose the same interruption state in the proof-on process.",
    ),
  },
  {
    id: "OPS-RESTART-003",
    family: "OPS-RESTART",
    title: "Stop after setMany and before buffer clear",
    component: "batch writer retry",
    sources: stakingServiceSources,
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "unresolved",
    policyIds: ["POL-020"],
    fixture: "restart-set-many-buffer-seed-203",
    proofOff: record(
      "Expose whether retry creates exactly one committed effect.",
    ),
    proofOn: record("Expose the same retry result in the proof-on process."),
  },
  {
    id: "OPS-RESTART-004",
    family: "OPS-RESTART",
    title: "Stop during WAL checkpoint",
    component: "SQLite checkpoint",
    sources: stakingServiceSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "restart-wal-stress-seed-204",
    proofOff: accept(
      "SQLite reopens to one transactionally valid state; label instruction timing as stress.",
    ),
    proofOn: accept(
      "SQLite has the same valid-state requirement in the proof-on process.",
    ),
  },
  {
    id: "OPS-RESTART-005",
    family: "OPS-RESTART",
    title: "Stop during checkpoint copy",
    component: "SQLite checkpoint copy",
    sources: checkpointSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "restart-partial-checkpoint-copy-seed-205",
    proofOff: reject(
      "STORAGE_FAILURE",
      "Resume does not select the partial checkpoint copy.",
    ),
    proofOn: reject(
      "STORAGE_FAILURE",
      "The proof-on process rejects the same partial copy.",
    ),
  },
  {
    id: "OPS-RESTART-006",
    family: "OPS-RESTART",
    title: "Stop during S3 checkpoint transfer",
    component: "checkpoint object storage",
    sources: checkpointSources,
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "unresolved",
    policyIds: ["POL-023"],
    fixture: "restart-s3-partial-transfer-seed-206",
    proofOff: record(
      "Expose whether a content digest rejects each partial object.",
    ),
    proofOn: record(
      "Expose the same production binding separately from proof validity.",
    ),
  },
  {
    id: "OPS-RESTART-007",
    family: "OPS-RESTART",
    title: "Stop after enqueue and before listener setup",
    component: "task queue completion",
    sources: queueSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "restart-enqueue-listener-gap-seed-207",
    proofOff: accept(
      "Immediate completion reaches the caller without an unbounded wait.",
    ),
    proofOn: accept("The same result occurs in the proof-on process."),
  },
  {
    id: "OPS-RESTART-008",
    family: "OPS-RESTART",
    title: "Stop during worker proof generation",
    component: "proof worker publication",
    sources: workerSources,
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "proof-authenticity",
    policyStatus: "unresolved",
    policyIds: ["POL-022"],
    fixture: "restart-worker-proof-generation-seed-208",
    proofOff: record(
      "The capability control confirms that no partial result is published.",
    ),
    proofOn: reject(
      "DEPENDENCY_FAILURE",
      "The killed proof task publishes no partial proof and uses an isolated retry.",
    ),
  },
  {
    id: "OPS-RESTART-009",
    family: "OPS-RESTART",
    title: "Stop after worker result and before proof persistence",
    component: "proof callback atomicity",
    sources: [...workerSources, ...stakingProofStorageSources],
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "unresolved",
    policyIds: ["POL-020"],
    fixture: "restart-result-persistence-gap-seed-209",
    proofOff: record(
      "Expose the permitted retry result after persistence failure.",
    ),
    proofOn: record(
      "Expose the same callback boundary in the proof-on process.",
    ),
  },
  {
    id: "OPS-RESTART-010",
    family: "OPS-RESTART",
    title: "Stop during base proof persistence",
    component: "base proof storage",
    sources: stakingProofStorageSources,
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "unresolved",
    policyIds: ["POL-020", "POL-023"],
    fixture: "restart-base-proof-persist-seed-210",
    proofOff: record(
      "Expose the atomic unit for setProof and its batch write.",
    ),
    proofOn: record(
      "Expose the same publication unit in the proof-on process.",
    ),
  },
  {
    id: "OPS-RESTART-011",
    family: "OPS-RESTART",
    title: "Stop during merge root publication",
    component: "merge proof publication",
    sources: mergeSources,
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "unresolved",
    policyIds: ["POL-023"],
    fixture: "restart-merge-root-publication-seed-211",
    proofOff: record(
      "Expose whether a failed root write leaves an accepted completion marker.",
    ),
    proofOn: record(
      "Expose the same atomic publication boundary in the proof-on process.",
    ),
  },
  {
    id: "OPS-RESTART-012",
    family: "OPS-RESTART",
    title: "Stop during proof file write",
    component: "proof file publication",
    sources: stakingProofStorageSources,
    claims: ["PROOF_AUTHENTICITY"],
    priority: "P0",
    phasePolicy: "proof-authenticity",
    policyStatus: "conformance",
    fixture: "restart-truncated-proof-file-seed-212",
    proofOff: record(
      "The capability control does not treat the truncated file as proof evidence.",
    ),
    proofOn: reject(
      "INPUT_VALIDATION",
      "A truncated proof file never yields accepted authenticity evidence.",
    ),
  },
  {
    id: "OPS-RESTART-013",
    family: "OPS-RESTART",
    title: "Stop during done or proven marker creation",
    component: "completion marker publication",
    sources: checkpointSources,
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "unresolved",
    policyIds: ["POL-023"],
    fixture: "restart-marker-creation-seed-213",
    proofOff: record(
      "Record the blocked production-seam requirement for atomic marker recovery.",
    ),
    proofOn: record("Record the same blocked production-seam requirement."),
  },
  {
    id: "OPS-RESTART-014",
    family: "OPS-RESTART",
    title: "Redis disconnect retry exhaustion and stall",
    component: "task queue Redis dependency",
    sources: queueSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "restart-redis-fault-partitions-seed-214",
    proofOff: reject(
      "DEPENDENCY_FAILURE",
      "Each Redis fault has bounded failure or approved recovery.",
    ),
    proofOn: reject(
      "DEPENDENCY_FAILURE",
      "Each Redis fault has the same bounded outcome.",
    ),
  },
  {
    id: "OPS-RESTART-015",
    family: "OPS-RESTART",
    title: "Two schedulers share one queue or lifecycle",
    component: "queue and lifecycle ownership",
    sources: [...queueSources, ...mergeSources],
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "unresolved",
    policyIds: ["POL-021"],
    fixture: "restart-two-schedulers-seed-215",
    proofOff: record(
      "Expose cross-scheduler deletion, completion, and listener effects.",
    ),
    proofOn: record(
      "Expose the same ownership behavior in the proof-on process.",
    ),
  },
  {
    id: "OPS-RESTART-016",
    family: "OPS-RESTART",
    title: "Invalid checkpoint resume selection",
    component: "checkpoint restore",
    sources: checkpointSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "checkpoint-absent-corrupt-stale-hash-root-seed-216",
    proofOff: reject(
      "STORAGE_FAILURE",
      "Do not resume from absent, corrupt, stale, wrong-hash, or wrong-root checkpoints.",
    ),
    proofOn: reject(
      "STORAGE_FAILURE",
      "The proof-on process rejects the same checkpoint partitions.",
    ),
  },
  {
    id: "OPS-RESTART-017",
    family: "OPS-RESTART",
    title: "Checkpoint signal and cleanup interruption recovery",
    component: "checkpoint lifecycle",
    sources: checkpointSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "checkpoint-cleanup-sigterm-hard-kill-seed-217",
    proofOff: accept(
      "A new run selects only a complete valid checkpoint after each interruption.",
    ),
    proofOn: accept(
      "The proof-on run applies the same checkpoint selection rule.",
    ),
  },
  {
    id: "OPS-RESTART-018",
    family: "OPS-RESTART",
    title: "Invalid completion marker rejection",
    component: "completion marker restore",
    sources: checkpointSources,
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "unresolved",
    policyIds: ["POL-023"],
    fixture: "marker-empty-missing-proof-corrupt-pointer-seed-218",
    proofOff: record(
      "Expose acceptance of empty, stale, proofless, changed-proof, or corrupt markers.",
    ),
    proofOn: record(
      "Expose the same marker binding separately from proof authenticity.",
    ),
  },
  {
    id: "OPS-RESTART-019",
    family: "OPS-RESTART",
    title: "Durable store reopen consistency",
    component: "durable recovery",
    sources: [...stakingServiceSources, ...stakingProofStorageSources],
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "restart-durable-state-cross-product-seed-219",
    proofOff: accept(
      "Reopen and match roots, counts, records, traces, proofs, files, and next indices.",
    ),
    proofOn: accept(
      "The reopened proof-on stores match the same state dimensions.",
    ),
  },
  {
    id: "OPS-RESTART-020",
    family: "OPS-RESTART",
    title: "API rejects incomplete SQLite publication",
    component: "API readiness",
    sources: [
      {
        path: "apps/api/src/processor-status-routes.ts",
        symbols: ["assertProcessorReady", "createProcessorStatusRoutes"],
      },
      ...stakingServiceSources,
    ],
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "api-incomplete-sqlite-publication-seed-220",
    proofOff: reject(
      "HOST_PREFLIGHT",
      "File existence alone does not make the lifecycle database ready.",
    ),
    proofOn: reject(
      "HOST_PREFLIGHT",
      "The proof-on API applies the same readiness rule.",
    ),
  },

  {
    id: "CALL-INTENT-001",
    family: "CALL-INTENT",
    title: "Immutable deployment intent parity across CLI and Web",
    component: "deployment configuration",
    sources: [
      {
        path: "devops/scripts/export-public-deployment-config.mjs",
        symbols: [
          "buildPublicDeploymentRecord",
          "exportPublicDeploymentConfig",
        ],
      },
      ...webProverSources,
    ],
    claims: ["EXTERNAL_PARITY"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "caller-immutable-deployment-seed-301",
    proofOff: accept(
      "CLI and Web normalize every shared deployment field to equal intent.",
    ),
    proofOn: accept("The same normalized intent is used before proof-on work."),
  },
  {
    id: "CALL-INTENT-002",
    family: "CALL-INTENT",
    title: "Missing blank malformed and conflicting configuration rejection",
    component: "deployment configuration",
    sources: [
      {
        path: "devops/scripts/export-public-deployment-config.mjs",
        symbols: ["buildPublicDeploymentRecord"],
      },
      ...webProverSources,
    ],
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "caller-invalid-config-partitions-seed-302",
    proofOff: reject(
      "INPUT_VALIDATION",
      "Each invalid shared field fails before transaction construction.",
    ),
    proofOn: reject(
      "INPUT_VALIDATION",
      "Each invalid field fails before compile or proving.",
    ),
  },
  {
    id: "CALL-INTENT-003",
    family: "CALL-INTENT",
    title: "CLI option precedence over environment",
    component: "CLI configuration",
    sources: [
      {
        path: "apps/cli/src/commands/treasury-owner.ts",
        symbols: [
          "treasuryOwnerCommandFactory",
          "compileTreasuryOwner",
          "deployTreasuryOwner",
        ],
      },
    ],
    claims: ["HOST"],
    priority: "P1",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "caller-cli-env-conflicts-seed-303",
    proofOff: accept(
      "The explicit CLI option wins for every documented conflicting value.",
    ),
    proofOn: accept("The proof-on command resolves the same value."),
  },
  {
    id: "CALL-INTENT-004",
    family: "CALL-INTENT",
    title: "Lifecycle identifier boundary validation",
    component: "caller lifecycle input",
    sources: [
      {
        path: "apps/cli/src/commands/treasury-owner.ts",
        symbols: ["deployTreasuryOwner", "readTreasuryOwnerState"],
      },
      ...webProverSources,
    ],
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "caller-lifecycle-zero-max-overflow-seed-304",
    proofOff: accept(
      "Accept in-domain boundary values and reject values outside UInt32.",
    ),
    proofOn: accept("The proof-on callers apply the same domain rule."),
  },
  {
    id: "CALL-INTENT-005",
    family: "CALL-INTENT",
    title: "Browser config precedes dynamic o1js import",
    component: "browser proof worker",
    sources: webProverSources,
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "caller-worker-config-before-import-seed-305",
    proofOff: accept(
      "The worker installs runtime config before its first dynamic import.",
    ),
    proofOn: accept(
      "The proof-on worker preserves the same initialization order.",
    ),
  },
  {
    id: "CALL-INTENT-006",
    family: "CALL-INTENT",
    title: "Browser compile artifacts match deployment",
    component: "browser proof worker",
    sources: webProverSources,
    claims: ["EXTERNAL_PARITY"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "caller-worker-compile-artifacts-seed-306",
    proofOff: accept(
      "Compile artifacts match all deployment keys, hashes, roots, and mode.",
    ),
    proofOn: accept(
      "The proof-on artifacts match the deployment and paired identities.",
    ),
  },
  {
    id: "CALL-INTENT-007",
    family: "CALL-INTENT",
    title: "Browser proof-authorized update carries an encoded proof",
    component: "browser transaction authorization",
    sources: webProverSources,
    claims: ["CONTRACT"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "caller-create-vote-execute-proof-auth-seed-307",
    proofOff: accept(
      "Each create, vote, and execute update has its required authorization shape.",
    ),
    proofOn: accept(
      "Each proof-authorized update carries the expected encoded current proof.",
    ),
  },
  {
    id: "CALL-INTENT-008",
    family: "CALL-INTENT",
    title: "Browser signature authorization identifies each signer",
    component: "browser transaction authorization",
    sources: webProverSources,
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "caller-required-signers-seed-308",
    proofOff: accept(
      "Each signature-authorized update identifies its required signer.",
    ),
    proofOn: accept(
      "The same signer set is present in the proof-on transaction.",
    ),
  },
  {
    id: "CALL-INTENT-009",
    family: "CALL-INTENT",
    title: "Browser authorization kind does not change silently",
    component: "browser transaction authorization",
    sources: webProverSources,
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "caller-authorization-kind-mutations-seed-309",
    proofOff: reject(
      "TRANSACTION_PRECONDITION",
      "Reject each undeclared authorization-kind change.",
    ),
    proofOn: reject(
      "TRANSACTION_PRECONDITION",
      "Reject the same change before submission.",
    ),
  },
  {
    id: "CALL-INTENT-010",
    family: "CALL-INTENT",
    title: "Concurrent browser requests keep compile modes isolated",
    component: "browser proof worker",
    sources: webProverSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "caller-worker-concurrent-modes-seed-310",
    proofOff: accept(
      "Concurrent requests cannot mix compile modes or deployment artifacts.",
    ),
    proofOn: accept("The proof-on worker keeps the same request isolation."),
  },
  {
    id: "CALL-INTENT-011",
    family: "CALL-INTENT",
    title: "Browser termination cancellation timeout and retry are bounded",
    component: "browser proof worker",
    sources: webProverSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "caller-worker-lifecycle-faults-seed-311",
    proofOff: reject(
      "TIMEOUT",
      "Each fault ends in a bounded response and leaves no mixed request state.",
    ),
    proofOn: reject(
      "TIMEOUT",
      "The proof-on worker has the same bounded cleanup.",
    ),
  },
  {
    id: "CALL-INTENT-012",
    family: "CALL-INTENT",
    title: "Stale browser compile result rejection after config change",
    component: "browser proof worker",
    sources: webProverSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "caller-worker-stale-compile-seed-312",
    proofOff: reject(
      "HOST_PREFLIGHT",
      "A config change invalidates the older compile result.",
    ),
    proofOn: reject(
      "HOST_PREFLIGHT",
      "The proof-on worker rejects the same stale artifact.",
    ),
  },
  {
    id: "CALL-INTENT-013",
    family: "CALL-INTENT",
    title: "Software and mock Ledger signer intent parity",
    component: "CLI Ledger signer",
    sources: [
      {
        path: "apps/cli/src/commands/multisig-sign.ts",
        symbols: [
          "signPauseTreasury",
          "signUnpauseTreasury",
          "signTogglePauseProposal",
          "signRotateMultisigKeys",
        ],
      },
    ],
    claims: ["EXTERNAL_PARITY"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "caller-software-mock-ledger-intent-seed-313",
    proofOff: accept(
      "Software and mock Ledger paths produce equal normalized intent.",
    ),
    proofOn: accept("The proof-on process produces the same caller intent."),
  },
  {
    id: "CALL-INTENT-014",
    family: "CALL-INTENT",
    title: "Ledger signer position and non-signer role matrix",
    component: "CLI Ledger signer",
    sources: [
      {
        path: "apps/cli/src/commands/treasury-owner.ts",
        symbols: [
          "deployTreasuryOwner",
          "transferToTreasury",
          "emergencyWithdraw",
        ],
      },
    ],
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "caller-role-position-variability-seed-314",
    proofOff: accept(
      "Every signer position signs and value-only recipients do not become signers.",
    ),
    proofOn: accept("The proof-on transaction requires the same role set."),
  },
  {
    id: "CALL-INTENT-015",
    family: "CALL-INTENT",
    title: "Same-key role collision policy",
    component: "caller role assignment",
    sources: [
      {
        path: "apps/cli/src/commands/treasury-owner.ts",
        symbols: [
          "deployTreasuryOwner",
          "transferToTreasury",
          "emergencyWithdraw",
        ],
      },
    ],
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "unresolved",
    policyIds: ["POL-028"],
    fixture: "caller-role-collision-matrix-seed-315",
    proofOff: record(
      "Record accepted and rejected role collisions until the policy is approved.",
    ),
    proofOn: record("Record the same role outcomes in the proof-on process."),
  },
  {
    id: "CALL-INTENT-016",
    family: "CALL-INTENT",
    title: "Wrong Ledger network account signer and payload rejection",
    component: "CLI Ledger signer",
    sources: [
      {
        path: "apps/cli/src/commands/multisig-sign.ts",
        symbols: [
          "signPauseTreasury",
          "signTogglePauseProposal",
          "signRotateMultisigKeys",
        ],
      },
    ],
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "caller-ledger-wrong-input-cross-product-seed-316",
    proofOff: reject(
      "INPUT_VALIDATION",
      "Each wrong signing-intent field fails before signature acceptance.",
    ),
    proofOn: reject(
      "INPUT_VALIDATION",
      "The proof-on caller rejects the same wrong fields.",
    ),
  },
  {
    id: "CALL-INTENT-017",
    family: "CALL-INTENT",
    title: "Ledger disconnect refusal timeout and partial response",
    component: "CLI Ledger signer",
    sources: [
      {
        path: "apps/cli/src/commands/multisig-sign.ts",
        symbols: [
          "signPauseTreasury",
          "signUnpauseTreasury",
          "signTogglePauseProposal",
          "signRotateMultisigKeys",
        ],
      },
    ],
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "caller-ledger-device-faults-seed-317",
    proofOff: reject(
      "DEPENDENCY_FAILURE",
      "Each device fault rejects cleanly with no accepted partial signature.",
    ),
    proofOn: reject(
      "DEPENDENCY_FAILURE",
      "The proof-on caller has the same clean failure.",
    ),
  },
  {
    id: "CALL-INTENT-018",
    family: "CALL-INTENT",
    title: "Physical Ledger device evidence exception",
    component: "CLI Ledger signer",
    sources: [
      {
        path: "apps/cli/src/commands/multisig-sign.ts",
        symbols: ["multisigSignCommandFactory"],
      },
    ],
    claims: ["UNRESOLVED"],
    priority: "P1",
    phasePolicy: "external-exception",
    policyStatus: "unresolved",
    policyIds: ["POL-034"],
    fixture: "caller-physical-ledger-lane-seed-318",
    proofOff: notApplicable(
      "Hosted CI has no approved physical-device evidence lane.",
    ),
    proofOn: notApplicable(
      "Hosted CI has no approved physical-device evidence lane.",
    ),
  },

  {
    id: "CALL-PROJECTION-001",
    family: "CALL-PROJECTION",
    title: "Accepted event contract-state and projection agreement",
    component: "proposal event projection",
    sources: projectionSources,
    claims: ["CONTRACT"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "projection-full-event-lifecycle-seed-401",
    proofOff: accept(
      "Each accepted event agrees with contract state and the final projection.",
    ),
    proofOn: accept(
      "The proof-on lifecycle has the same normalized projection.",
    ),
  },
  {
    id: "CALL-PROJECTION-002",
    family: "CALL-PROJECTION",
    title: "Duplicate archive event idempotence",
    component: "event ingestion",
    sources: projectionSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "projection-duplicate-events-seed-402",
    proofOff: accept(
      "A duplicate event produces one durable projection effect.",
    ),
    proofOn: accept(
      "The proof-on process produces the same idempotent effect.",
    ),
  },
  {
    id: "CALL-PROJECTION-003",
    family: "CALL-PROJECTION",
    title: "Delayed and reordered archive event convergence",
    component: "event ingestion",
    sources: projectionSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "projection-delay-reorder-permutations-seed-403",
    proofOff: accept(
      "Valid delayed and reordered inputs converge to the canonical projection.",
    ),
    proofOn: accept("The proof-on process converges to the same projection."),
  },
  {
    id: "CALL-PROJECTION-004",
    family: "CALL-PROJECTION",
    title: "Orphaned and superseded event handling",
    component: "event ingestion",
    sources: projectionSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "projection-orphan-supersession-seed-404",
    proofOff: accept(
      "Orphaned facts retire and superseded failures do not block canonical work.",
    ),
    proofOn: accept("The proof-on process has the same retirement result."),
  },
  {
    id: "CALL-PROJECTION-005",
    family: "CALL-PROJECTION",
    title: "Canonical-chain rollback and replay",
    component: "event projection replay",
    sources: projectionSources,
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "projection-chain-fork-replay-seed-405",
    proofOff: accept(
      "Rollback removes prior-chain effects and replay builds only the new canonical state.",
    ),
    proofOn: accept(
      "The proof-on process reaches the same canonical projection.",
    ),
  },
  {
    id: "CALL-PROJECTION-006",
    family: "CALL-PROJECTION",
    title: "Incomplete lifecycle database readiness rejection",
    component: "API lifecycle projection",
    sources: [
      {
        path: "apps/api/src/processor-status-routes.ts",
        symbols: ["assertProcessorReady", "createProcessorStatusRoutes"],
      },
    ],
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "projection-incomplete-lifecycle-db-seed-406",
    proofOff: reject(
      "HOST_PREFLIGHT",
      "The API rejects the incomplete lifecycle database.",
    ),
    proofOn: reject(
      "HOST_PREFLIGHT",
      "The API rejects the same database in the proof-on process.",
    ),
  },
  {
    id: "CALL-PROJECTION-007",
    family: "CALL-PROJECTION",
    title: "Projection evidence does not claim proof validity",
    component: "event consumer trust boundary",
    sources: projectionSources,
    claims: ["CHARACTERIZATION"],
    priority: "P1",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "projection-evidence-boundary-seed-407",
    proofOff: record(
      "Label accepted-event evidence as projection evidence only.",
    ),
    proofOn: record(
      "Do not convert proof-on process execution into proof-authenticity credit.",
    ),
  },

  {
    id: "E2E-LOCAL-001",
    family: "E2E-LOCAL",
    title: "Complete LocalBlockchain treasury lifecycle",
    component: "local end-to-end lifecycle",
    sources: localBlockchainSources,
    claims: ["CONTRACT", "PROOF_MODE_PARITY"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "local-full-flow-role-and-ledger-variability-seed-501",
    proofOff: accept(
      "Create, vote, tally, and execute with expected state, events, balances, and projection.",
    ),
    proofOn: accept(
      "Use current STLV and reducer proofs and match the proof-off semantic transcript.",
    ),
  },
  {
    id: "E2E-LOCAL-002",
    family: "E2E-LOCAL",
    title: "Local proof-consuming transaction acceptance",
    component: "local proof consumer",
    sources: localBlockchainSources,
    claims: ["PROOF_AUTHENTICITY", "CONTRACT"],
    priority: "P0",
    phasePolicy: "proof-authenticity",
    policyStatus: "conformance",
    fixture: "local-proof-consumer-current-artifacts-seed-502",
    proofOff: record(
      "The negative control records proof-disabled transaction capability.",
    ),
    proofOn: accept(
      "A current valid proof is consumed by the intended contract transaction.",
    ),
  },
  {
    id: "E2E-LOCAL-003",
    family: "E2E-LOCAL",
    title: "Local permissions signer and negative-combination matrix",
    component: "local contract authorization",
    sources: localBlockchainSources,
    claims: ["CONTRACT"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "local-auth-negative-cross-product-seed-503",
    proofOff: reject(
      "TRANSACTION_PRECONDITION",
      "Each invalid permission or signer combination leaves state unchanged.",
    ),
    proofOn: reject(
      "TRANSACTION_PRECONDITION",
      "The proof-on flow rejects the same combinations.",
    ),
  },

  {
    id: "E2E-LIGHTNET-001",
    family: "E2E-LIGHTNET",
    title: "Lightnet proof-on-only phase exception",
    component: "Lightnet execution policy",
    sources: [
      {
        path: "apps/api/test/e2e/proposal-lifecycle-lightnet.e2e.ts",
        symbols: ["proposal lifecycle Lightnet suite"],
      },
    ],
    claims: ["UNRESOLVED"],
    priority: "P0",
    phasePolicy: "lightnet-operational",
    policyStatus: "unresolved",
    policyIds: ["POL-024"],
    fixture: "lightnet-exception-approval-seed-601",
    proofOff: notApplicable(
      "No real proof-off Lightnet flow exists; approval is required.",
    ),
    proofOn: record(
      "Run only after the proof-on operational exception is approved.",
    ),
  },
  {
    id: "E2E-LIGHTNET-002",
    family: "E2E-LIGHTNET",
    title: "Current-proof Lightnet full service flow",
    component: "Lightnet end-to-end lifecycle",
    sources: [
      {
        path: "apps/api/test/e2e/proposal-lifecycle-lightnet.e2e.ts",
        symbols: ["proposal lifecycle Lightnet suite"],
      },
      ...stakingServiceSources,
      ...queueSources,
      ...workerSources,
      ...mergeSources,
    ],
    claims: ["PROOF_AUTHENTICITY", "RESILIENCE"],
    priority: "P0",
    phasePolicy: "lightnet-operational",
    policyStatus: "unresolved",
    policyIds: ["POL-024"],
    fixture: "lightnet-current-proof-full-services-seed-602",
    proofOff: notApplicable(
      "No real proof-off Lightnet full-service flow exists.",
    ),
    proofOn: accept(
      "Generate current proofs through SQLite, Redis, worker, merge, exhaust, tally, and API projection.",
    ),
  },
  {
    id: "E2E-LIGHTNET-003",
    family: "E2E-LIGHTNET",
    title: "Lightnet network-operation variability",
    component: "Lightnet network behavior",
    sources: [
      {
        path: "apps/api/test/e2e/proposal-lifecycle-lightnet.e2e.ts",
        symbols: ["proposal lifecycle Lightnet suite"],
      },
    ],
    claims: ["RESILIENCE"],
    priority: "P0",
    phasePolicy: "lightnet-operational",
    policyStatus: "unresolved",
    policyIds: ["POL-024"],
    fixture: "lightnet-graphql-slot-fee-nonce-retry-seed-603",
    proofOff: notApplicable(
      "No equivalent real proof-off network lane exists.",
    ),
    proofOn: accept(
      "Cover GraphQL, inclusion, archive delay, slots, fees, nonce contention, retry, and state refresh.",
    ),
  },

  {
    id: "QA-COVERAGE-001",
    family: "QA-COVERAGE",
    title: "Node LCOV source-map validity",
    component: "coverage reporting",
    sources: [
      {
        path: "devops/scripts/run-node-test-coverage.mjs",
        symbols: ["expectedSourceFiles", "PER_FILE_LINE_MINIMUM"],
      },
    ],
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "coverage-known-ts-line-and-branch-seed-701",
    proofOff: accept(
      "LCOV maps one known TypeScript line and branch and includes every expected source file.",
    ),
    proofOn: accept(
      "Proof-on LCOV passes the same mapping check as a separate diagnostic flag.",
    ),
  },
  {
    id: "QA-COVERAGE-002",
    family: "QA-COVERAGE",
    title: "Local coverage thresholds and explicit file rows",
    component: "coverage gate",
    sources: [
      {
        path: "devops/scripts/run-node-test-coverage.mjs",
        symbols: [
          "PER_FILE_LINE_MINIMUM",
          "expectedSourceFiles",
          "belowMinimum",
          "missingSourceFiles",
        ],
      },
    ],
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "coverage-global-and-per-file-thresholds-seed-702",
    proofOff: accept(
      "Require 80% lines, 80% functions, 75% branches, and 60% lines per included file.",
    ),
    proofOn: record(
      "Keep proof-on coverage diagnostic and separate from the proof-off security claim.",
    ),
  },
  {
    id: "QA-COVERAGE-003",
    family: "QA-COVERAGE",
    title: "Frozen coverage denominator and reviewed exclusions",
    component: "coverage denominator",
    sources: [
      {
        path: "devops/scripts/run-node-test-coverage.mjs",
        symbols: ["expectedSourceFiles", "excludes"],
      },
    ],
    claims: ["STATIC_ONLY"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "coverage-denominator-manifest-seed-703",
    proofOff: accept(
      "The frozen denominator lists every source and each owned exclusion.",
    ),
    proofOn: accept("The proof-on report uses the same source denominator."),
  },
  {
    id: "QA-COVERAGE-004",
    family: "QA-COVERAGE",
    title: "Phase B Codecov configuration and upload closure",
    component: "Codecov reporting",
    sources: [
      {
        path: ".github/workflows/backend.yml",
        symbols: ["backend workflow coverage artifacts"],
      },
      {
        path: "apps/web/vitest.config.ts",
        symbols: ["vitest configuration"],
      },
      {
        path: "apps/backoffice/vitest.config.ts",
        symbols: ["vitest configuration"],
      },
      {
        path: "packages/ui/vitest.config.ts",
        symbols: ["vitest configuration"],
      },
    ],
    claims: ["CHARACTERIZATION"],
    priority: "P1",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "coverage-codecov-preflight-seed-704",
    proofOff: record(
      "Report NOT_CONFIGURED until Phase B adds providers, flags, uploads, and gates.",
    ),
    proofOn: record(
      "Do not claim Codecov success from proof-on semantic execution.",
    ),
  },
  {
    id: "QA-COVERAGE-005",
    family: "QA-COVERAGE",
    title: "Semantic assurance report closure",
    component: "assurance reporting",
    sources: [
      {
        path: "packages/sdk/test/assurance/case-types.ts",
        symbols: ["expandCaseLeaves"],
      },
      {
        path: "packages/sdk/test/assurance/case-manifest.ts",
        symbols: ["summarizeManifest", "validateManifest"],
      },
    ],
    claims: ["HOST"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "coverage-semantic-report-closure-seed-705",
    proofOff: accept(
      "Report manifest, mutation, rejection-layer, recursion, key, serialization, contract, restart, and vector totals.",
    ),
    proofOn: accept(
      "Report the proof-on leaf difference and every approved exception.",
    ),
  },
  {
    id: "QA-COVERAGE-006",
    family: "QA-COVERAGE",
    title: "Missing current Codecov flag cannot carry forward",
    component: "Codecov reporting",
    sources: [
      {
        path: ".github/workflows/backend.yml",
        symbols: ["backend workflow coverage artifacts"],
      },
    ],
    claims: ["STATIC_ONLY"],
    priority: "P1",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "coverage-missing-flag-seed-706",
    proofOff: reject(
      "HOST_PREFLIGHT",
      "A missing current blocking upload cannot use an older report.",
    ),
    proofOn: reject(
      "HOST_PREFLIGHT",
      "The diagnostic proof-on flag also reports its current absence.",
    ),
  },

  {
    id: "QA-PERFORMANCE-001",
    family: "QA-PERFORMANCE",
    title: "Cold and warm native operation calibration",
    component: "proof performance",
    sources: [
      ...workerSources,
      ...mergeSources,
      {
        path: "packages/sdk/src/proving/prover/staking-ledger-to-voting-ledger-prover.ts",
        symbols: [
          "StakingLedgerToVotingLedgerProver.digest",
          "StakingLedgerToVotingLedgerProver.exhaust",
        ],
      },
    ],
    claims: ["PERFORMANCE"],
    priority: "P1",
    phasePolicy: "proof-authenticity",
    policyStatus: "conformance",
    fixture: "performance-cold-3-warm-5-seed-801",
    proofOff: record(
      "Record proof-off compile, queue, storage, serialized size, and RSS observations.",
    ),
    proofOn: record(
      "Collect at least three cold and five warm observations for each expensive native operation.",
    ),
  },
  {
    id: "QA-PERFORMANCE-002",
    family: "QA-PERFORMANCE",
    title: "Complete sample key and p95 publication threshold",
    component: "performance statistics",
    sources: workerSources,
    claims: ["PERFORMANCE"],
    priority: "P1",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "performance-sample-key-40-observations-seed-802",
    proofOff: record(
      "Before 40 observations, publish each value, median, range, and maximum without p95.",
    ),
    proofOn: record(
      "Publish p95 only with 40 observations and the complete hardware, software, cache, fixture, and runner key.",
    ),
  },
  {
    id: "QA-PERFORMANCE-003",
    family: "QA-PERFORMANCE",
    title: "Cold and warm cache semantic equality",
    component: "proof cache performance",
    sources: [...mergeSources, ...stakingProofStorageSources],
    claims: ["PROOF_MODE_PARITY"],
    priority: "P0",
    phasePolicy: "paired-semantic",
    policyStatus: "conformance",
    fixture: "performance-cache-semantic-parity-seed-803",
    proofOff: accept(
      "Cold and warm runs have equal public values, state commitments, key identities, and effects.",
    ),
    proofOn: accept(
      "The proof-on cache run matches semantics without requiring equal proof bytes or timing.",
    ),
  },
  {
    id: "QA-PERFORMANCE-004",
    family: "QA-PERFORMANCE",
    title: "Operation-specific absolute and relative budgets",
    component: "performance gate",
    sources: [...workerSources, ...mergeSources, ...stakingServiceSources],
    claims: ["PERFORMANCE"],
    priority: "P1",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "performance-operation-budget-registry-seed-804",
    proofOff: record(
      "Keep the gate inactive until each operation has approved absolute and relative limits.",
    ),
    proofOn: record(
      "After approval, each independent limit blocks its matching operation.",
    ),
  },
  {
    id: "QA-PERFORMANCE-005",
    family: "QA-PERFORMANCE",
    title: "Scheduled production-shape liveness and capacity soak",
    component: "operations capacity",
    sources: [
      ...workerSources,
      ...queueSources,
      ...stakingServiceSources,
      ...checkpointSources,
    ],
    claims: ["PERFORMANCE", "RESILIENCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "performance-loss-backlog-fee-capacity-seed-805",
    proofOff: record(
      "Measure worker, Redis, SQLite, S3, archive, lifecycle, backlog, memory, and fee-payer limits.",
    ),
    proofOn: record(
      "Use production-shape fixtures; a small fixture does not establish full-ledger capacity.",
    ),
  },
  {
    id: "QA-PERFORMANCE-006",
    family: "QA-PERFORMANCE",
    title: "Performance runs exclude coverage instrumentation",
    component: "performance harness",
    sources: [
      {
        path: "devops/scripts/run-node-test-coverage.mjs",
        symbols: ["args", "child"],
      },
      ...workerSources,
    ],
    claims: ["PERFORMANCE"],
    priority: "P0",
    phasePolicy: "host-dual",
    policyStatus: "conformance",
    fixture: "performance-no-coverage-preflight-seed-806",
    proofOff: accept(
      "The performance process starts without coverage instrumentation.",
    ),
    proofOn: accept(
      "The proof-on performance process also starts without instrumentation.",
    ),
  },
]);
